name: Child 2 Workflow

on:
  workflow_run:
    workflows: ["Child 1 Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔗 Child 2 triggered after Child 1"
