name: Child 5 Workflow

on:
  workflow_run:
    workflows: ["Child 4 Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔗 Child 5 triggered after Child 4"
