name: Child 8 Workflow

on:
  workflow_run:
    workflows: ["Child 7 Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔗 Child 8 triggered after Child 7"
