name: Child 9 Workflow

on:
  workflow_run:
    workflows: ["Child 8 Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔗 Child 9 triggered after Child 8"
