name: Child 4 Workflow

on:
  workflow_run:
    workflows: ["Child 3 Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔗 Child 4 triggered after Child 3"
