name: Child 1 Workflow

on:
  workflow_run:
    workflows: ["Parent Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔗 Child 1 triggered after Parent"
