name: Parent Workflow

on:
  push:
    branches:  
      - main 
permissions:
  contents: read
  actions: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 Parent workflow" 
